package de.gaz.eedu.course.appointment;


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import de.gaz.eedu.course.CourseEntity;
import de.gaz.eedu.course.appointment.model.CourseAppointmentModel;
import de.gaz.eedu.course.appointment.entry.AppointmentEntryEntity;
import de.gaz.eedu.entity.model.EntityModelRelation;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;

import java.time.Instant;
import java.time.Period;
import java.time.temporal.ChronoUnit;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Setter @Entity @Getter @NoArgsConstructor
public class CourseAppointmentEntity implements EntityModelRelation<CourseAppointmentModel>
{
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Setter(AccessLevel.NONE) private long id;
    @JsonBackReference @ManyToOne(optional = false) @JoinColumn(name = "course_id", referencedColumnName = "id")
    private CourseEntity course;
    private Instant timeStamp;
    private Period period;

    @OneToMany(mappedBy = "courseAppointment") @JsonManagedReference
    @Getter(AccessLevel.NONE)
    private final Set<AppointmentEntryEntity> entries = new HashSet<>();

    @Override public @NotNull CourseAppointmentModel toModel()
    {
        //TODO
        return null;
    }

    private boolean part(@NotNull Instant timeStamp)
    {
        if(timeStamp.isBefore(getTimeStamp()))
        {
            return false;
        }

        long between = ChronoUnit.SECONDS.between(getTimeStamp(), timeStamp);
        long period = getPeriod().get(ChronoUnit.DAYS) * 24 * 60 * 60;

        return between % period == 0;
    }

    @Override public String toString()
    { // Automatically generated by IntelliJ
        return "CourseAppointmentEntity{" +
                "id=" + id +
                ", course=" + course +
                ", start=" + timeStamp +
                ", period=" + period +
                ", entries=" + entries +
                '}';
    }

    public boolean setAppointmentEntry(@NotNull CourseAppointmentService service, @NotNull AppointmentEntryEntity entry)
    {
        if(setAppointmentEntry(entry))
        {
            service.saveEntity(this);
            return true;
        }
        return false;
    }

    public boolean setAppointmentEntry(@NotNull AppointmentEntryEntity entry)
    {
        return entries.add(entry);
    }

    public @NotNull AppointmentEntryEntity[] getEntries()
    {
        return entries.toArray(AppointmentEntryEntity[]::new);
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        CourseAppointmentEntity that = (CourseAppointmentEntity) object;
        return getId() == that.getId();
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hashCode(getId());
    }
}
