package de.gaz.eedu.course.appointment;


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import de.gaz.eedu.course.CourseEntity;
import de.gaz.eedu.course.appointment.entry.AppointmentEntryEntity;
import de.gaz.eedu.course.appointment.model.CourseAppointmentModel;
import de.gaz.eedu.entity.model.EntityModelRelation;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;

import java.time.Duration;
import java.time.Instant;
import java.time.Period;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Setter @Entity @Getter @NoArgsConstructor
public class CourseAppointmentEntity implements EntityModelRelation<CourseAppointmentModel>
{
    @OneToMany(mappedBy = "courseAppointment") @JsonManagedReference @Getter(AccessLevel.NONE)
    private final Set<AppointmentEntryEntity> entries = new HashSet<>();
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Setter(AccessLevel.NONE) private long id;
    @JsonBackReference @ManyToOne(optional = false) @JoinColumn(name = "course_id", referencedColumnName = "id")
    private CourseEntity course;
    private Instant timeStamp;
    private Duration duration;
    private Period period;

    @Override public @NotNull CourseAppointmentModel toModel()
    {
        return new CourseAppointmentModel(getId(), getTimeStamp().getEpochSecond(), getPeriodSeconds());
    }

    public boolean inPeriod(@NotNull Instant timeStamp)
    {
        if (getTimeStamp().isAfter(timeStamp))
        {
            return false;
        }
        return sinus(getTimeStamp().getEpochSecond()) == sinus(timeStamp.getEpochSecond());
    }

    private double sinus(long timeStamp)
    {
        return Math.sin(2 * Math.PI * ((double) timeStamp / (getPeriodSeconds() * 2)));
    }

    public boolean setAppointmentEntry(@NotNull CourseAppointmentService service, @NotNull AppointmentEntryEntity entry)
    {
        if (setAppointmentEntry(entry))
        {
            service.saveEntity(this);
            return true;
        }
        return false;
    }

    public boolean setAppointmentEntry(@NotNull AppointmentEntryEntity entry)
    {
        return entries.add(entry);
    }

    public @NotNull AppointmentEntryEntity[] getEntries()
    {
        return entries.toArray(AppointmentEntryEntity[]::new);
    }

    public long getPeriodSeconds()
    {
        return (long) this.getPeriod().getDays() * 24 * 60 * 60;
    }

    @Override public String toString()
    { // Automatically generated by IntelliJ
        return "CourseAppointmentEntity{" + "id=" + id + ", course=" + course + ", timeStamp=" + timeStamp + ", duration=" + duration + ", period=" + period + ", entries=" + entries + '}';
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        CourseAppointmentEntity that = (CourseAppointmentEntity) object;
        return getId() == that.getId();
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hashCode(getId());
    }
}
