package de.gaz.sp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpApplication {

    public static void main(String[] args) { // Automatically generated by IntelliJ
        SpringApplication.run(SpApplication.class, args);
    }

}
