package de.gaz.eedu.course.classroom.model;

import de.gaz.eedu.course.classroom.ClassRoomEntity;
import de.gaz.eedu.entity.model.CreationModel;
import lombok.NonNull;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record ClassRoomCreateModel(
        @NonNull String id,
        @NotNull Long tutor,
        @NotNull Long[] students,
        @NotNull Long[] courses
) implements CreationModel<String, ClassRoomEntity>
{

    @Override
    public @NotNull ClassRoomEntity toEntity(@NotNull ClassRoomEntity entity)
    {
        return entity;
    }

    @Contract(pure = true, value = "-> new")
    @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ClassRoomCreateModel{" +
                "id='" + id + '\'' +
                ", tutor=" + tutor +
                ", students=" + Arrays.toString(students) +
                ", courses=" + Arrays.toString(courses) +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        ClassRoomCreateModel that = (ClassRoomCreateModel) o;
        return Objects.equals(id(), that.id());
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
