package de.gaz.eedu.course.classroom.model;

import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.model.ReducedUserModel;
import lombok.NonNull;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record ClassRoomModel(
        @NonNull Long id,
        @NonNull String name,
        @NotNull ReducedUserModel tutor,
        @NonNull ReducedUserModel[] students
) implements EntityModel <Long> {

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ClassRoomModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", tutor=" + tutor +
                ", students=" + Arrays.toString(students) +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        ClassRoomModel that = (ClassRoomModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
