package de.gaz.eedu.course.classroom.model;

import de.gaz.eedu.course.classroom.ClassRoomEntity;
import de.gaz.eedu.entity.model.CreationModel;
import lombok.NonNull;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record ClassRoomCreateModel (
        @NonNull String name,
        @NotNull Long tutor,
        @NotNull Long[] students,
        @NotNull Long[] courses
) implements CreationModel<ClassRoomEntity> {

    @Override
    public @NotNull ClassRoomEntity toEntity(@NotNull ClassRoomEntity entity)
    {
        entity.setName(name());
        return entity;
    }

    @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ClassRoomCreateModel{" +
                "name='" + name + '\'' +
                ", tutor=" + tutor +
                ", students=" + Arrays.toString(students) +
                ", courses=" + Arrays.toString(courses) +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        ClassRoomCreateModel that = (ClassRoomCreateModel) o;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(name);
    }
}
