package de.gaz.eedu.user.group;

import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.privileges.PrivilegeEntity;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;
import java.util.Set;

public record GroupModel(@Nullable Long id, @NotEmpty(message = "Name must not be empty.") String name,
                         Set<UserEntity> userEntities, Set<PrivilegeEntity> privilegeEntities) {

    @Contract(pure = true)
    @Override
    public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "GroupModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", userEntities=" + userEntities +
                ", privilegeEntities=" + privilegeEntities +
                '}';
    }

    @Override
    public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        GroupModel that = (GroupModel) object;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
