package de.gaz.eedu.user.group.model;


import de.gaz.eedu.entity.model.CreationModel;
import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.privileges.PrivilegeEntity;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import java.util.Set;

public record GroupCreateModel(@NotNull String name, @NotNull Set<UserEntity> users,
                               @NotNull Set<PrivilegeEntity> privileges) implements CreationModel<GroupEntity>
{
    @Override public @NotNull GroupEntity toEntity()
    {
        GroupEntity groupEntity = new GroupEntity();
        groupEntity.setName(name());
        groupEntity.setUsers(users());
        groupEntity.setPrivileges(privileges());
        return groupEntity;
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    {  // Automatically generated by IntelliJ
        return "GroupCreateModel{" +
                "name='" + name + '\'' +
                ", users=" + users +
                ", privileges=" + privileges +
                '}';
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        GroupCreateModel that = (GroupCreateModel) object;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hash(name);
    }
}
