package de.gaz.eedu.user.group.model;

import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.privileges.model.PrivilegeModel;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record GroupModel(@NotNull Long id, @NotEmpty(message = "Name must not be empty.") String name,
                         @NotNull PrivilegeModel[] privileges) implements EntityModel
{


    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "GroupModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        GroupModel that = (GroupModel) object;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
