package de.gaz.eedu.user.group.model;

import de.gaz.eedu.entity.model.Model;
import de.gaz.eedu.user.model.SimpleUserModel;
import de.gaz.eedu.user.privileges.model.SimplePrivilegeModel;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import java.util.Set;

public record GroupModel(@NotNull Long id, @NotEmpty(message = "Name must not be empty.") String name,
                         @NotNull Set<SimpleUserModel> users,
                         @NotNull Set<SimplePrivilegeModel> privileges) implements Model
{

    @Contract(pure = true)
    @Override
    public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "GroupModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", users=" + users +
                ", privileges=" + privileges +
                '}';
    }

    @Override
    public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        GroupModel that = (GroupModel) object;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
