package de.gaz.eedu.user.group.model;


import de.gaz.eedu.entity.model.CreationModel;
import de.gaz.eedu.user.group.GroupEntity;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record GroupCreateModel(@NotNull String id, @NotNull String[] privileges) implements CreationModel<String, GroupEntity>
{
    @Override public @NotNull GroupEntity toEntity(@NotNull GroupEntity groupEntity)
    {
        return groupEntity;
    }


    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "GroupCreateModel{" +
                "id='" + id + '\'' +
                ", privileges=" + Arrays.toString(privileges) +
                '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object)
        {
            return true;
        }
        if (object == null || getClass() != object.getClass())
        {
            return false;
        }
        GroupCreateModel that = (GroupCreateModel) object;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
