package de.gaz.eedu.user.group.model;


import de.gaz.eedu.entity.model.CreationModel;
import de.gaz.eedu.user.group.GroupEntity;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record GroupCreateModel(@NotNull String name, @NotNull Boolean twoFactorRequired, @NotNull Long[] users,
                               @NotNull Long[] privileges) implements CreationModel<GroupEntity>
{
    @Override public @NotNull GroupEntity toEntity(@NotNull GroupEntity groupEntity)
    {
        groupEntity.setName(name());
        groupEntity.setTwoFactorRequired(twoFactorRequired());
        return groupEntity;
    }

    @Override public @NotNull String toString()
    {
        return "GroupCreateModel{" + "name='" + name + '\'' + ", twoFactorRequired=" + twoFactorRequired + ", users=" + Arrays.toString(
                users) + ", privileges=" + Arrays.toString(privileges) + '}';
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object)
        {
            return true;
        }
        if (object == null || getClass() != object.getClass())
        {
            return false;
        }
        GroupCreateModel that = (GroupCreateModel) object;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hash(name);
    }
}
