package de.gaz.eedu.user.verfication.model;

import de.gaz.eedu.user.model.LoginModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record AdvancedUserLoginModel(@NotNull String loginName, @NotNull String password) implements LoginModel
{
    @Contract(pure = true)
    @Override
    public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "AdvancedUserLoginModel{" + "loginName='" + loginName + '\'' + ", password='" + password + '\'' + '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        AdvancedUserLoginModel that = (AdvancedUserLoginModel) o;
        return Objects.equals(loginName, that.loginName) && Objects.equals(password, that.password);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(loginName, password);
    }
}
