package de.gaz.eedu.user.verfication.model;

import de.gaz.eedu.user.model.LoginModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record UserLoginModel(@NotNull String loginName, @NotNull String password,
                             @NotNull Boolean keepLoggedIn) implements LoginModel
{
    @Contract(pure = true)
    @Override
    public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "UserLoginModel{" + "loginName='" + loginName + '\'' + ", password='" + password + '\'' + ", keepLoggedIn=" + keepLoggedIn + '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        UserLoginModel that = (UserLoginModel) o;
        return Objects.equals(loginName, that.loginName) && Objects.equals(password, that.password) && Objects.equals(
                keepLoggedIn,
                that.keepLoggedIn);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(loginName, password, keepLoggedIn);
    }
}
