POST http://localhost:8080/user/login
Content-Type: application/json

{
  "loginName": "root",
  "password": "SafePassword123!!."
}

###
POST http://localhost:8080/user/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk5MTcyMTI3fQ.XAsh1pChVFvWqzazcCX-JKtTIADh-uA1PdqlZIYMg28

{
  "loginName": "root",
  "password": "SafePassword123!!."
}

###
GET http://localhost:8080/user/get/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk5MTcyMTI3fQ.XAsh1pChVFvWqzazcCX-JKtTIADh-uA1PdqlZIYMg28

###
POST http://localhost:8080/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk5MTcyODIwfQ.QTWoEfmVMQTN4QzPaoFyG0WEEr6PuP20zFMErKsgpTg

{
  "firstName": "John",
  "lastName": "Doe",
  "loginName": "asdasf",
  "password": "testPass123!",
  "enabled": true,
  "locked": false,
  "themeId": 0
}
