###
@host = http://localhost:8080/
@user = 1

@login_name = "root"
@login_password = "Development123!"

###
GET {{host}}/user/get/{{user}}

### Log in
POST {{host}}/user/login
Content-Type: application/json

{
  "loginName": {{login_name}},
  "password": {{login_password}},
  "keepLoggedIn": true
}

### Verify 2fa
GET {{host}}/user/login/twofactor/verify/1111
Authorization: Bearer

### Log in advanced
POST {{host}}/user/login/advanced
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBVVRIT1JJWkVEIiwidXNlcklEIjoxLCJleHAiOjE3MDcxMjY0NzQsImlhdCI6MTcwNTkxNjg3NH0.Xv4VZe6MEnQJxzwCH28rgZcbbwhYkXTZ6ykm4P1vIR8

{
  "loginName": {{login_name}},
  "password": {{login_password}}
}

### Create chat
POST localhost:8080/chat/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBRFZBTkNFRF9BVVRIT1JJWkFUSU9OIiwidXNlcklEIjoxLCJleHAiOjE3MDIyMTE0NzQsImlhdCI6MTcwMjEyNTA3NH0.YuzS96y6wzL37NNuabgByLtVjvqlpyWU44EB0AYGwQs

[0, 1]

###
POST {{host}}/user/login/twofactor/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBRFZBTkNFRF9BVVRIT1JJWkFUSU9OIiwidXNlcklEIjoxLCJleHAiOjE3MDYwMDM2MjksImlhdCI6MTcwNTkxNzIyOX0.YXrFJ-zeFmDl336Pv9Otz73fP4UThn99S6OPK9HTyek

{
  "userID": 1,
  "data": "",
  "method": "TOTP"
}

### Enable two factor
GET {{host}}/user/login/twofactor/enable/TOTP/204106
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBRFZBTkNFRF9BVVRIT1JJWkFUSU9OIiwidXNlcklEIjoxLCJleHAiOjE3MDIyMTE0NzQsImlhdCI6MTcwMjEyNTA3NH0.YuzS96y6wzL37NNuabgByLtVjvqlpyWU44EB0AYGwQs
