###
POST http://localhost:8080/user/login
Content-Type: application/json

{
"loginName": "root",
"password": "SafePassword123!!."
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
"loginName": "asdasf",
"password": "SafePassword123!!."
}

###
GET http://localhost:8080/user/me/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk4NTI5ODEzfQ.8GcKKYHFq-TczCrCAZCqUxneoKSr_9xW5VkmmT9yYns

###
POST http://localhost:8080/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk4NTI5ODEzfQ.8GcKKYHFq-TczCrCAZCqUxneoKSr_9xW5VkmmT9yYns

{
"firstName": "John",
"lastName": "Doe",
"loginName": "asdasf",
"password": "testPass123!",
"enabled": true,
"locked": false,
"groupEntities": []
}
