package de.gaz.sp.user;

import de.gaz.sp.user.group.GroupEntity;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import java.util.Set;

/**
 * Represents a {@link UserEntity} as model.
 * <p>
 * This class is responsible for interacting with the user system in the {@link UserService} as it provides a convenient
 * and easy method to send json over http.
 * This then can be used to store the data in the user database and transform this model into a real user object.
 *
 * @param id of the user.
 * @param firstName of the user.
 * @param lastName of the user.
 * @param email of the user.
 * @param password of the user.
 * @param enabled whether the user allowed to log in.
 * @param locked whether the user allowed to log in.
 * @param groupEntities groups this user is in.
 *
 * @see UserEntity
 * @see GroupEntity
 * @author ivo
 */
public record UserModel(@Nullable Long id, @NotEmpty String firstName, @NotEmpty String lastName,
                        @NotEmpty String email, @NotEmpty(message = "Password must not be empty.") String password,
                        @NotEmpty Boolean enabled, @NotEmpty Boolean locked, Set<GroupEntity> groupEntities) {

    @Contract(pure = true)
    @Override
    public @NotNull String toString() { // Automatically generated by IntelliJ
        return "UserModel{" + "id=" + id + ", firstName='" + firstName + '\'' + ", lastName='" + lastName + '\'' + ", email='" + email + '\'' + ", password='" + password + '\'' + ", enabled=" + enabled + ", locked=" + locked + ", groupEntities=" + groupEntities + '}';
    }

    @Override
    public boolean equals(Object object) { // Automatically generated by IntelliJ
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        UserModel userModel = (UserModel) object;
        return Objects.equals(id, userModel.id);
    }

    @Override
    public int hashCode() { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
