package de.gaz.eedu.user.model;

import de.gaz.eedu.user.AccountType;
import jakarta.validation.constraints.NotNull;
import org.jetbrains.annotations.Contract;

import java.util.Objects;

public record ReducedUserModel(@NotNull Long id, @NotNull String firstName, @NotNull String lastName, @NotNull AccountType accountType)
{
    @Contract(pure = true) @Override public @org.jetbrains.annotations.NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ReducedUserModel{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", accountType=" + accountType +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        ReducedUserModel that = (ReducedUserModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
