package de.gaz.eedu.user.model;

import de.gaz.eedu.course.classroom.model.ClassRoomModel;
import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.AccountType;
import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.UserService;
import de.gaz.eedu.user.UserStatus;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.group.model.GroupModel;
import de.gaz.eedu.user.theming.ThemeModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

/**
 * Represents a {@link UserEntity} as model.
 * <p>
 * This class is responsible for interacting with the user system in the {@link UserService} as it provides a
 * convenient
 * and easy method to send json over http.
 * This then can be used to store the data in the user database and transform this model into a real user object.
 *
 * @param id        of the user.
 * @param firstName of the user.
 * @param lastName  of the user.
 * @param groups    groups this user is in.
 * @param status
 * @author ivo
 * @see UserEntity
 * @see GroupEntity
 */
public record UserModel(
        @NotNull Long id,
        @NotNull String firstName,
        @NotNull String lastName,
        @NotNull String loginName,
        @NotNull AccountType accountType,
        @NotNull UserStatus status,
        @NotNull GroupModel[] groups,
        @NotNull ThemeModel theme,
        @Nullable ClassRoomModel classroom
) implements EntityModel<Long> {

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "UserModel{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", loginName='" + loginName + '\'' +
                ", accountType=" + accountType +
                ", status=" + status +
                ", groups=" + Arrays.toString(groups) +
                ", theme=" + theme +
                ", classroom=" + classroom +
                '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        UserModel userModel = (UserModel) object;
        return Objects.equals(id, userModel.id);
    }

    public @NotNull ReducedUserModel toReducedModel()
    {
        return new ReducedUserModel(id(), firstName(), lastName(), accountType());
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
