package de.gaz.eedu.user.model;

import de.gaz.eedu.entity.model.Model;
import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.UserService;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.group.model.SimpleUserGroupModel;
import de.gaz.eedu.user.theming.ThemeEntity;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import java.util.Set;

/**
 * Represents a {@link UserEntity} as model.
 * <p>
 * This class is responsible for interacting with the user system in the {@link UserService} as it provides a
 * convenient
 * and easy method to send json over http.
 * This then can be used to store the data in the user database and transform this model into a real user object.
 *
 * @param id        of the user.
 * @param firstName of the user.
 * @param lastName  of the user.
 * @param enabled   whether the user allowed to log in.
 * @param locked    whether the user allowed to log in.
 * @param groups    groups this user is in.
 * @author ivo
 * @see UserEntity
 * @see GroupEntity
 */
public record UserModel(@NotNull Long id, @NotEmpty String firstName, @NotEmpty String lastName,
                        @NotEmpty String loginName,
                        @NotEmpty Boolean enabled, @NotEmpty Boolean locked,
                        @NotEmpty ThemeEntity themeEntity, //TODO remove entity
                        @NotEmpty Set<SimpleUserGroupModel> groups) implements Model
{

    @Override public String toString()
    {
        return "UserModel{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", loginName='" + loginName + '\'' +
                ", enabled=" + enabled +
                ", locked=" + locked +
                ", theme=" + themeEntity.getName() +
                ", groups=" + groups +
                '}';
    }

    @Override
    public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        UserModel userModel = (UserModel) object;
        return Objects.equals(id, userModel.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
