package de.gaz.eedu.course.subjects.model;

import de.gaz.eedu.course.subjects.SubjectEntity;
import de.gaz.eedu.entity.model.CreationModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record SubjectCreateModel(@NotNull String name) implements CreationModel<SubjectEntity>
{
    @Override
    public @NotNull SubjectEntity toEntity(@NotNull SubjectEntity entity)
    {
        entity.setName(name());
        return entity;
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "SubjectCreateModel{" +
                "name='" + name + '\'' +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        SubjectCreateModel that = (SubjectCreateModel) o;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(name);
    }
}
