package de.gaz.eedu.course.appointment.model;

import de.gaz.eedu.course.appointment.WeekDay;
import de.gaz.eedu.entity.model.EntityModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.time.Duration;
import java.util.Objects;

public record CourseAppointmentModel(@NotNull Long id, @NotNull Long start, @NotNull Long period) implements EntityModel
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CourseAppointmentModel{" +
                "id=" + id +
                ", start=" + start +
                ", period=" + period +
                '}';
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        CourseAppointmentModel that = (CourseAppointmentModel) object;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    {  // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
