package de.gaz.eedu.course.appointment.scheduled.model;

import de.gaz.eedu.entity.model.EntityModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record ScheduledAppointmentModel(@NotNull Long id, @NotNull Long start, @NotNull Long end, @NotNull Long duration, @NotNull Long period) implements EntityModel
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ScheduledAppointmentModel{" +
                "id=" + id +
                ", start=" + start +
                ", duration=" + duration +
                ", period=" + period +
                '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        ScheduledAppointmentModel that = (ScheduledAppointmentModel) object;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
