package de.gaz.eedu.user.verfication.authority;

import de.gaz.eedu.user.verfication.JwtTokenType;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.springframework.security.core.GrantedAuthority;

import java.util.Objects;

public record VerificationAuthority(@NotNull JwtTokenType jwtTokenType) implements GrantedAuthority
{
    @Override
    public @NotNull String getAuthority()
    {
        return jwtTokenType().toString();
    }

    @Override
    public boolean equals(@NotNull Object o)
    { // Automatically generated by IntelliJ
        if (this == o)
        { return true; }
        if (getClass() != o.getClass()) { return false; }
        VerificationAuthority that = (VerificationAuthority) o;
        return jwtTokenType == that.jwtTokenType;
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(jwtTokenType);
    }
}
