package de.gaz.eedu.course.room.model;

import de.gaz.eedu.course.room.RoomEntity;
import de.gaz.eedu.entity.model.CreationModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record RoomCreateModel(@NotNull String id) implements CreationModel<String, RoomEntity>
{
    @Override public @NotNull RoomEntity toEntity(@NotNull RoomEntity entity) {return entity;}

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "RoomCreateModel{" + "id='" + id + '\'' + '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        RoomCreateModel that = (RoomCreateModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
