package de.gaz.eedu.user.privileges;

import com.fasterxml.jackson.annotation.JsonBackReference;
import de.gaz.eedu.entity.model.EntityModelRelation;
import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.group.model.SimplePrivilegeGroupModel;
import de.gaz.eedu.user.model.SimpleUserModel;
import de.gaz.eedu.user.privileges.model.PrivilegeModel;
import de.gaz.eedu.user.privileges.model.SimplePrivilegeModel;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.util.Objects;
import java.util.Set;

@Entity @Getter @AllArgsConstructor @NoArgsConstructor @Setter @Table(name = "privilege_entity") public class PrivilegeEntity implements EntityModelRelation<PrivilegeModel>
{

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Setter(AccessLevel.NONE) // ID is final
    private Long id;
    private String name;
    @JsonBackReference @ManyToMany(mappedBy = "privileges") private Set<GroupEntity> groupEntities;

    public @NotNull SimplePrivilegeModel toSimpleModel()
    {
        return new SimplePrivilegeModel(getId(), getName());
    }

    @Override public PrivilegeModel toModel()
    {
        return new PrivilegeModel(getId(),
                getName(),
                getGroupEntities().stream()
                        .map(groupEntity -> new SimplePrivilegeGroupModel(groupEntity.getId(),
                                groupEntity.getName(),
                                groupEntity.getUsers()
                                        .stream()
                                        .map(UserEntity::toSimpleModel)
                                        .toArray(SimpleUserModel[]::new)))
                        .distinct()
                        .toArray(SimplePrivilegeGroupModel[]::new));
    }

    @Override public String toString()
    { // Automatically generated by IntelliJ
        return "PrivilegeEntity{" + "id=" + id + ", name='" + name + '\'' + ", groupEntities=" + groupEntities + '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        PrivilegeEntity that = (PrivilegeEntity) object;
        return Objects.equals(getId(), that.getId());
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(getId());
    }
}
