package de.gaz.eedu.user.privileges;

import com.fasterxml.jackson.annotation.JsonBackReference;
import de.gaz.eedu.entity.model.EntityModelRelation;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.privileges.model.PrivilegeModel;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.jetbrains.annotations.Contract;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Entity @Getter @AllArgsConstructor @NoArgsConstructor @Setter @Table(name = "privilege_entity")
public class PrivilegeEntity implements EntityModelRelation<String, PrivilegeModel>
{
    @Id @Setter(AccessLevel.NONE) @Column(length = 50) private String id;
    @JsonBackReference @ManyToMany(mappedBy = "privileges", fetch = FetchType.LAZY)
    private final Set<GroupEntity> groupEntities = new HashSet<>();

    public @NotNull SimpleGrantedAuthority toAuthority()
    {
        return new SimpleGrantedAuthority(getId());
    }

    @Override public PrivilegeModel toModel()
    {
        return new PrivilegeModel(getId());
    }

    @Override public boolean isDeletable()
    {
        return !SystemPrivileges.isSystemPrivilege(getId());
    }

    @Contract(pure = true) @Override public String toString()
    { // Automatically generated by IntelliJ
        return "PrivilegeEntity{" +
                "id='" + id + '\'' +
                ", groupEntities=" + groupEntities +
                '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        PrivilegeEntity that = (PrivilegeEntity) object;
        return Objects.equals(getId(), that.getId());
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(getId());
    }
}