package de.gaz.eedu.user.privileges;

import de.gaz.eedu.user.group.GroupEntity;
import jakarta.validation.constraints.NotEmpty;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;
import java.util.Set;

/**
 * This represents a {@link PrivilegeEntity}.
 * <p>
 * This model exists to effectively create a json friendly
 * object which can be easily ported into a {@link PrivilegeEntity}.
 * It simplifies the workflow when using the rest api.
 * <p>
 * Note that the only way to interact with this is by using the {@link PrivilegeService}.
 * It provides all the necessary methods to create and edit privileges.
 *
 * @param id
 * @param name
 * @author ivo
 * @see PrivilegeService
 */
public record PrivilegeModel(
        @Nullable Long id,
        @NotEmpty(message = "Name must be not empty.") @NotNull String name,
        Set<GroupEntity> groupEntities) {

    @Contract(pure = true)
    @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "PrivilegeModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", groupEntities=" + groupEntities +
                '}';
    }

    @Override
    public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        PrivilegeModel that = (PrivilegeModel) object;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
