package de.gaz.eedu.user.verification.credentials.model;

import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.verification.credentials.implementations.CredentialMethod;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import java.util.Objects;

public record CredentialModel(@NotNull Long id, @NotNull CredentialMethod method, boolean enabled) implements EntityModel<Long>
{
    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CredentialModel{" +
                "id=" + id +
                ", method=" + method +
                ", enabled=" + enabled +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) {return true;}
        if (o == null || getClass() != o.getClass()) {return false;}
        CredentialModel that = (CredentialModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(id);
    }
}
