package de.gaz.eedu.user.verification.credentials.model;

import de.gaz.eedu.user.verification.credentials.implementations.CredentialMethod;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

public record TemporaryCredentialCreateModel(
        @NotNull CredentialMethod method,
        @Nullable String data,
        @NotNull CredentialMethod... allowed
)
{

    public int bitMask()
    {
        return CredentialMethod.bitMask(allowed());
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "TemporaryCredentialCreateModel{" +
                "method=" + method +
                ", data='" + data + '\'' +
                ", allowed=" + Arrays.toString(allowed) +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        TemporaryCredentialCreateModel that = (TemporaryCredentialCreateModel) o;
        return Objects.equals(data, that.data) && method == that.method && Objects.deepEquals(
                allowed,
                that.allowed);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(method, data, Arrays.hashCode(allowed));
    }
}
