package de.gaz.eedu.user.verification.credentials.model;

import de.gaz.eedu.user.verification.credentials.implementations.CredentialMethod;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

public record UndefinedCredentialCreateModel(
        @NotNull CredentialMethod method,
        @Nullable String data
)
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "UndefinedCredentialCreateModel{" +
                "method=" + method +
                ", data='" + data + '\'' +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        UndefinedCredentialCreateModel that = (UndefinedCredentialCreateModel) o;
        return Objects.equals(data, that.data) && method == that.method;
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hash(method, data);
    }
}
