package de.gaz.eedu.user.privileges.model;

import de.gaz.eedu.entity.model.CreationModel;
import de.gaz.eedu.user.group.GroupEntity;
import de.gaz.eedu.user.privileges.PrivilegeEntity;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;
import java.util.stream.Collectors;

public record PrivilegeCreateModel(@NotNull String name,
                                   @NotNull GroupEntity[] groupEntities) implements CreationModel<PrivilegeEntity>
{
    @Override public @NotNull PrivilegeEntity toEntity(@NotNull PrivilegeEntity privilegeEntity)
    {
        privilegeEntity.setName(name().toUpperCase()); // Make privileges always uppercase
        privilegeEntity.setGroupEntities(Arrays.stream(groupEntities).collect(Collectors.toSet()));
        return privilegeEntity;
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    {  // Automatically generated by IntelliJ
        return "PrivilegeCreateModel{" + "name='" + name + '\'' + ", groupEntities=" + Arrays.toString(groupEntities) + '}';
    }

    @Override public boolean equals(Object object)
    {  // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        PrivilegeCreateModel that = (PrivilegeCreateModel) object;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    {
        return Objects.hash(name);
    }
}
