package de.gaz.eedu;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class EEDUApplication {

    public static void main(String[] args) { // Automatically generated by IntelliJ
        SpringApplication.run(EEDUApplication.class, args);
    }

}
