package de.gaz.eedu;

import de.gaz.eedu.security.PrivilegeProperties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties(PrivilegeProperties.class)
public class EEDUApplication {

    public static void main(String[] args) { // Automatically generated by IntelliJ
        SpringApplication.run(EEDUApplication.class, args);
    }

}
