package de.gaz.eedu.course.subject.model;

import de.gaz.eedu.course.subject.SubjectEntity;
import de.gaz.eedu.entity.model.CreationModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record SubjectCreateModel(@NotNull String id) implements CreationModel<String, SubjectEntity>
{
    @Override
    public @NotNull SubjectEntity toEntity(@NotNull SubjectEntity entity) { return entity; }

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "SubjectCreateModel{" +
                "id='" + id + '\'' +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (o == null || getClass() != o.getClass()) {return false;}
        SubjectCreateModel that = (SubjectCreateModel) o;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
