package de.gaz.eedu.course.subject.model;

import de.gaz.eedu.entity.model.EntityModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record SubjectModel(@NotNull String id) implements EntityModel<String>
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "SubjectModel{" +
                "id='" + id + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        SubjectModel that = (SubjectModel) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
