package de.gaz.eedu.course.appointment.frequent.model;

import de.gaz.eedu.course.room.model.RoomModel;
import de.gaz.eedu.entity.model.EntityModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

public record FrequentAppointmentModel(@NotNull Long id,
                                       @NotNull RoomModel room,
                                       @NotNull Long start,
                                       @NotNull Long end,
                                       @NotNull Long duration,
                                       @NotNull Long frequency) implements EntityModel
{

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ScheduledAppointmentModel{" +
                "id=" + id +
                ", start=" + start +
                ", duration=" + duration +
                ", frequency=" + frequency +
                '}';
    }

    @Override public boolean equals(Object object)
    { // Automatically generated by IntelliJ
        if (this == object) {return true;}
        if (object == null || getClass() != object.getClass()) {return false;}
        FrequentAppointmentModel that = (FrequentAppointmentModel) object;
        return Objects.equals(id, that.id);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
