package de.gaz.eedu.course.classroom;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import de.gaz.eedu.course.CourseEntity;
import de.gaz.eedu.course.classroom.exception.TutorConflictException;
import de.gaz.eedu.course.classroom.model.ClassRoomModel;
import de.gaz.eedu.course.model.CourseModel;
import de.gaz.eedu.entity.model.EntityModelRelation;
import de.gaz.eedu.user.UserEntity;
import de.gaz.eedu.user.model.UserModel;
import jakarta.persistence.*;
import lombok.*;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

@Entity @Getter @Setter @AllArgsConstructor @NoArgsConstructor @Table(name = "class_room_entity")
public class ClassRoomEntity implements EntityModelRelation<ClassRoomModel>
{
    @OneToMany @JsonManagedReference
    @JoinTable(name = "class_users", joinColumns = @JoinColumn(name = "class_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"))
    private final Set<UserEntity> users = new HashSet<>();
    @OneToMany(mappedBy = "classRoom") @JsonBackReference private final Set<CourseEntity> courses = new HashSet<>();
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Setter(AccessLevel.NONE) private Long id;
    private String name;

    @Override public ClassRoomModel toModel()
    {
        //TODO
        return new ClassRoomModel(getId(), getName(), new UserModel[0], new CourseModel[0]);
    }

    public @NotNull Optional<UserEntity> getTutor()
    {
        return getUsers().stream().filter(user -> user.hasRole("teacher")).findFirst();
    }

    public boolean attachUsers(@NotNull ClassRoomService classRoomService, @NonNull UserEntity... user)
    {
        return saveEntityIfPredicateTrue(classRoomService, user, this::attachUsers);
    }

    public boolean attachUsers(@NonNull UserEntity... user)
    {
        // Filter already attached users out
        Predicate<UserEntity> predicate = present -> getUsers().stream().noneMatch(currentUser ->
        {
            if (present.hasRole("teacher") && currentUser.hasRole("teacher"))
            {
                throw new TutorConflictException();
            }

            return Objects.equals(present, currentUser);
        });

        return this.users.addAll(Arrays.stream(user).filter(predicate).collect(Collectors.toSet()));
    }

    public boolean detachUsers(@NotNull ClassRoomService classRoomService, @NonNull Long... ids)
    {
        return saveEntityIfPredicateTrue(classRoomService, ids, this::detachUsers);
    }

    public boolean detachUsers(@NonNull Long... ids)
    {
        List<Long> detachGroupIds = Arrays.asList(ids);
        return this.users.removeIf(user -> detachGroupIds.contains(user.getId()));
    }

    private <T> boolean saveEntityIfPredicateTrue(@NotNull ClassRoomService classRoomService, @NotNull T test, @NotNull Predicate<T> predicate)
    {
        if (predicate.test(test))
        {
            classRoomService.saveEntity(this);
            return true;
        }
        return false;
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "ClassRoomEntity{" + "id=" + id + ", name='" + name + '\'' + ", users=" + users + ", courses=" + courses + '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        ClassRoomEntity that = (ClassRoomEntity) o;
        return Objects.equals(getId(), that.getId());
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(getId());
    }
}
