package de.gaz.eedu.course.model;

import de.gaz.eedu.course.appointment.scheduled.model.ScheduledAppointmentModel;
import de.gaz.eedu.course.subjects.model.SubjectModel;
import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.model.UserModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record CourseModel(@NotNull Long id, @NotNull String name, @NotNull SubjectModel subject,
                          @NotNull UserModel[] users, @NotNull ScheduledAppointmentModel[] appointments) implements EntityModel
{

    @Contract(pure = true)
    @Override
    public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CourseModel{" + "id=" + id + ", name='" + name + '\'' + ", subject=" + subject + ", users=" + Arrays.toString(
                users) + '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        CourseModel that = (CourseModel) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
