package de.gaz.eedu.course.model;

import de.gaz.eedu.course.CourseEntity;
import de.gaz.eedu.entity.model.CreationModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

public record CourseCreateModel(
        @NotNull String name,
        @NotNull String subject,
        @NotNull Long teacher,
        @NotNull Long[] students,
        @Nullable Long classroom
) implements CreationModel<Long, CourseEntity> {

    @Override
    public @NotNull CourseEntity toEntity(@NotNull CourseEntity entity)
    {
        entity.setName(name());
        return entity;
    }

    @Override public String toString()
    { // Automatically generated by IntelliJ
        return "CourseCreateModel{" +
                "id='" + name + '\'' +
                ", subject=" + subject +
                ", teacher=" + teacher +
                ", students=" + Arrays.toString(students) +
                ", classroom=" + classroom +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) {return true;}
        if (o == null || getClass() != o.getClass()) {return false;}
        CourseCreateModel that = (CourseCreateModel) o;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(name);
    }
}
