package de.gaz.eedu.course.model;

import de.gaz.eedu.course.appointment.entry.model.AppointmentEntryModel;
import de.gaz.eedu.course.appointment.frequent.model.FrequentAppointmentModel;
import de.gaz.eedu.course.classroom.model.ClassRoomModel;
import de.gaz.eedu.course.subject.model.SubjectModel;
import de.gaz.eedu.entity.model.EntityModel;
import de.gaz.eedu.user.model.ReducedUserModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

public record CourseModel(
        @NotNull Long id,
        @NotNull String name,
        @NotNull SubjectModel subject,
        @NotNull ReducedUserModel[] students,
        @NotNull AppointmentEntryModel[] appointmentEntries,
        @NotNull FrequentAppointmentModel[] frequentAppointments,
        @Nullable ReducedUserModel teacher,
        @Nullable ClassRoomModel classRoom
) implements EntityModel<Long>
{

    @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CourseModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subject=" + subject +
                ", students=" + Arrays.toString(students) +
                ", appointmentEntries=" + Arrays.toString(appointmentEntries) +
                ", frequentAppointments=" + Arrays.toString(frequentAppointments) +
                ", classRoom=" + classRoom +
                ", teacher=" + teacher +
                '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) {return true;}
        if (o == null || getClass() != o.getClass()) {return false;}
        CourseModel that = (CourseModel) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
