package de.gaz.eedu.course.model;

import de.gaz.eedu.course.CourseEntity;
import de.gaz.eedu.entity.model.CreationModel;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Arrays;
import java.util.Objects;

public record CourseCreateModel(
        @NotNull String name,
        @NotNull Long subjectId,
        @Nullable Long classId,
        @NotNull Long[] users
) implements CreationModel<Long, CourseEntity> {

    @Override
    public @NotNull CourseEntity toEntity(@NotNull CourseEntity entity)
    {
        entity.setName(name());
        return entity;
    }

    @Contract(pure = true) @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CourseCreateModel{" +
                "name='" + name + '\'' +
                ", subjectId=" + subjectId +
                ", classId=" + classId +
                ", users=" + Arrays.toString(users) +
                '}';
    }

    @Override public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        CourseCreateModel that = (CourseCreateModel) o;
        return Objects.equals(name, that.name);
    }

    @Override public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(name);
    }
}
