package de.gaz.eedu.course.model;

import de.gaz.eedu.course.appointment.entry.model.AppointmentEntryModel;
import de.gaz.eedu.course.appointment.scheduled.model.ScheduledAppointmentModel;
import de.gaz.eedu.course.subject.model.SubjectModel;
import de.gaz.eedu.entity.model.EntityModel;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Objects;

public record CourseModel(@NotNull Long id, @NotNull String name, @NotNull SubjectModel subject, @NotNull AppointmentEntryModel[] appointmentEntries, @NotNull ScheduledAppointmentModel[] scheduledAppointments) implements EntityModel
{

    @Override public @NotNull String toString()
    { // Automatically generated by IntelliJ
        return "CourseModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subject=" + subject +
                ", entries=" + Arrays.toString(appointmentEntries) +
                ", appointments=" + Arrays.toString(scheduledAppointments) +
                '}';
    }

    @Override
    public boolean equals(Object o)
    { // Automatically generated by IntelliJ
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        CourseModel that = (CourseModel) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode()
    { // Automatically generated by IntelliJ
        return Objects.hashCode(id);
    }
}
